name: Komodo Electrum CI

on: [push, pull_request]

jobs:
  linux-ci:
    name: Linux
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Install deps (Linux)
        env:
          DEBIAN_FRONTEND: noninteractive
        if: runner.os == 'Linux'
        run: |
          sudo apt-get remove php7.1-fpm php7.2-fpm php7.3-fpm php7.4-fpm php7.3-common
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade -y
          sudo apt-get update
          sudo apt-get install -q \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 python3-pyqt5 \
                 pyqt5-dev-tools \
                 python-requests \
                 gettext \
                 python3-setuptools \
                 protobuf-compiler \
                 libusb-1.0-0-dev \
                 libudev-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install pytest
          python3 -m pip install .[full]

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          pyrcc5 icons.qrc -o gui/qt/icons_rc.py
          protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto
          ./contrib/make_locale

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          python3 -m pytest lib/tests/ -s -vv

